# Generated by Django 6.1.1 on 2026-09-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_cancion_duracion_ms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='duracion_ms',
            field=models.PositiveIntegerField(),
        ),
    ]
