# Generated by Django 6.1.1 on 2026-09-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_cancion_duracion_ms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=22, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('genero', models.CharField(blank=True, max_length=50)),
                ('subgenero', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='genero',
        ),
        migrations.AddField(
            model_name='cancion',
            name='playlists',
            field=models.ManyToManyField(related_name='canciones', to='catalogo.playlist'),
        ),
    ]
