# Generated by Django 6.1.2 on 2026-10-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_playlist_remove_cancion_genero_cancion_playlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='artista',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
